sudo: required
services:
  - docker

before_install: 
  - docker build -t christianharborow/react-test -f ./client/Dockerfile.dev ./client
  
script: 
  - docker run -e CI=true christianharborow/react-test npm test

after_success: 
  - docker build -t christianharborow/multi-client ./client
  - docker build -t christianharborow/multi-nginx ./nginx
  - docker build -t christianharborow/multi-server ./server
  - docker build -t christianharborow/multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push christianharborow/multi-client
  - docker push christianharborow/multi-nginx
  - docker push christianharborow/multi-server
  - docker push christianharborow/multi-worker

deploy:
  provider: elasticbeanstalk
  on:
    branch: main
  region: "eu-west-2"
  app: "multi-docker"
  env: "Multi-docker-env-1"
  bucket_name: "elasticbeanstalk-eu-west-2-767398143123"
  bucket_path: "multi-docker"
  access_key: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  